import 'package:fil/i10n/localization.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  int dateTime = 1639389988079;
  test("generate config ChineseCupertinoLocalizations", () async {
    ChineseCupertinoLocalizations local = ChineseCupertinoLocalizations();
    local.init();
    var alertDialogLabel = local.alertDialogLabel;
    var timerPickerHourLabels = local.timerPickerHourLabels;
    var timerPickerMinuteLabels = local.timerPickerMinuteLabels;
    var timerPickerSecondLabels = local.timerPickerSecondLabels;
    var anteMeridiemAbbreviation = local.anteMeridiemAbbreviation;
    local.searchTextFieldPlaceholderLabel;
    local.modalBarrierDismissLabel;
    local.todayLabel;
    local.datePickerDateOrder;
    local.datePickerDateTimeOrder;
    local.datePickerHourSemanticsLabel(dateTime);
    local.datePickerMediumDate(new DateTime.now());
    local.datePickerMinute(dateTime);
    local.datePickerMinuteSemanticsLabel(dateTime);
    var copyButtonLabel = local.copyButtonLabel;
    var cutButtonLabel= local.cutButtonLabel;
    var hours = local.datePickerHour(15);
    var dayOfMonth= local.datePickerDayOfMonth(12);
    var tabSemanticsLabel =local.tabSemanticsLabel(tabIndex:1,tabCount: 10);
    var month = local.datePickerMonth(12);
    var year = local.datePickerYear(2021);
    var button = local.pasteButtonLabel;
    var abbreviation = local.postMeridiemAbbreviation;
    var buttonLabel = local.selectAllButtonLabel;
    var hour = local.timerPickerHour(14);
    var hourLabel = local.timerPickerHourLabel(14);
    var minute = local.timerPickerMinute(30);
    var minuteLabel = local.timerPickerMinuteLabel(30);
    var second = local.timerPickerSecond(50);
    var secondLabel = local.timerPickerSecondLabel(50);
    expect(timerPickerHourLabels, ['']);
    expect(timerPickerMinuteLabels,['']);
    expect(timerPickerSecondLabels, ['']);
    expect(anteMeridiemAbbreviation, '上午');
    expect(copyButtonLabel, '复制');
    expect(cutButtonLabel, '剪切');
    expect(hours, '15');
    expect(dayOfMonth, '12');
    expect(tabSemanticsLabel, '第1页，共10页');
    expect(hour, '14');
    expect(hour, '14');
    expect(month, '12');
    expect(year, '2021');
    expect(alertDialogLabel, '提醒');
    expect(button, '粘贴');
    expect(abbreviation, '下午');
    expect(buttonLabel, '全选');
    expect(hourLabel, '14时');
    expect(minute, '30');
    expect(minuteLabel, '30分');
    expect(second, '50');
    expect(secondLabel, '50秒');
  });
}