name: fil
description:  fivetoken

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+19

environment:
  sdk: ">2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # git: https://gitlab.com/abu0306/flotus.git
  # git: https://gitlab.com/abu0306/bls.git
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7
  hive: any
  hive_flutter: any
  flutter_secure_storage: any
  path_provider: any
  bip39: any
  bip32: ^1.0.5
  dio: any
  crypto: any
  encrypt: any
  flotus: ^2.0.1
  bls: ^2.0.1
  permission_handler: 8.2.5
  image_gallery_saver: any
  get:
  qr_flutter: ^3.1.0
  flutter_slidable: ^0.5.7
  scan: ^0.0.7
  connectivity: any
  pull_to_refresh: any
  image_picker: any
  fbutton: ^2.0.1
  package_info: ^0.4.3+2
  webview_flutter: any
  device_info: any
  url_launcher: any
  gesture_password_widget: ^1.0.6
  share: any
  oktoast: any
  flutter_swipe_action_cell: ^1.3.4
  day: ^0.6.4
  uni_links: ^0.4.0
  cryptography: any
  logger: 0.9.4
  tuple: 1.0.3
  uuid: any
  web_socket_channel: any
  web3dart: 2.3.2
  random_color: ^1.0.5
  event_bus: ^1.1.1
  dio_log: any
  bloc: any
  flutter_bloc: any
  equatable: any
  http: any
  #flutter_local_notifications: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any
  mockito: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages