// Mocks generated by Mockito 5.0.16 from annotations
// in fil/test/request/ether_test.dart.
// Do not manually edit this file.

import 'package:fil/repository/web3/json_rpc.dart' as _i4;
import 'package:fil/request/ether.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:web3dart/web3dart.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Ether].
///
/// See the documentation for Mockito's code generation for more information.
class MockEther extends _i1.Mock implements _i2.Ether {
  MockEther() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Web3Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeb3Client extends _i1.Mock implements _i3.Web3Client {
  MockWeb3Client() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [RpcJson].
///
/// See the documentation for Mockito's code generation for more information.
class MockRpcJson extends _i1.Mock implements _i4.RpcJson {
  MockRpcJson() {
    _i1.throwOnMissingStub(this);
  }
}
