// Mocks generated by Mockito 5.1.0 from annotations
// in fil/test/request/filecoin_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:fil/common/shared_preferences.dart' as _i4;
import 'package:fil/repository/http/http.dart' as _i3;
import 'package:fil/request/filecoin.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Filecoin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilecoin extends _i1.Mock implements _i2.Filecoin {
  MockFilecoin() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Http].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttp extends _i1.Mock implements _i3.Http {
  MockHttp() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [PreferencesManagerX].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesManagerX extends _i1.Mock
    implements _i4.PreferencesManagerX {
  MockPreferencesManagerX() {
    _i1.throwOnMissingStub(this);
  }
}
