// Mocks generated by Mockito 5.1.0 from annotations
// in fil/test/pages/pass/reset_test.dart.
// Do not manually edit this file.

// @dart=2.9

import 'package:flutter/foundation.dart' as _i3;
import 'package:get/get_state_manager/get_state_manager.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GetX].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetX<T extends _i1.DisposableInterface> extends _i2.Mock
    implements _i1.GetX<T> {
  MockGetX() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String toString({_i3.DiagnosticLevel minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}
