// Mocks generated by Mockito 5.0.16 from annotations
// in fil/test/pages/home/widgets/net_test.dart.
// Do not manually edit this file.

import 'package:fil/store/store.dart' as _i3;
import 'package:hive/hive.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i2.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [StoreController].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreController extends _i1.Mock implements _i3.StoreController {
  MockStoreController() {
    _i1.throwOnMissingStub(this);
  }
}
