// Objective-C API for talking to gitlab.forceup.in/FilecoinWallet/FilWallet/wlib Go package.
//   gobind -lang=objc gitlab.forceup.in/FilecoinWallet/FilWallet/wlib
//
// File is generated by gobind. Do not edit.

#ifndef __Wlib_H__
#define __Wlib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WlibBigInt;
@class WlibMessage;
@class WlibMsg;

@interface WlibBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BigInt.Int with unsupported type: *math/big.Int

// skipped method BigInt.Abs with unsupported parameter or return types

// skipped method BigInt.Add with unsupported parameter or return types

// skipped method BigInt.And with unsupported parameter or return types

// skipped method BigInt.AndNot with unsupported parameter or return types

- (NSData* _Nullable)append:(NSData* _Nullable)buf base:(long)base;
// skipped method BigInt.Binomial with unsupported parameter or return types

// skipped method BigInt.Bit with unsupported parameter or return types

- (long)bitLen;
// skipped method BigInt.Bits with unsupported parameter or return types

- (NSData* _Nullable)bytes;
// skipped method BigInt.Cmp with unsupported parameter or return types

// skipped method BigInt.CmpAbs with unsupported parameter or return types

// skipped method BigInt.Div with unsupported parameter or return types

// skipped method BigInt.DivMod with unsupported parameter or return types

// skipped method BigInt.Exp with unsupported parameter or return types

// skipped method BigInt.Format with unsupported parameter or return types

// skipped method BigInt.GCD with unsupported parameter or return types

- (BOOL)gobDecode:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)gobEncode:(NSError* _Nullable* _Nullable)error;
- (int64_t)int64;
- (BOOL)isInt64;
- (BOOL)isUint64;
// skipped method BigInt.Lsh with unsupported parameter or return types

// skipped method BigInt.MarshalCBOR with unsupported parameter or return types

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)marshalText:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.Mod with unsupported parameter or return types

// skipped method BigInt.ModInverse with unsupported parameter or return types

// skipped method BigInt.ModSqrt with unsupported parameter or return types

// skipped method BigInt.Mul with unsupported parameter or return types

// skipped method BigInt.MulRange with unsupported parameter or return types

// skipped method BigInt.Neg with unsupported parameter or return types

// skipped method BigInt.Not with unsupported parameter or return types

// skipped method BigInt.Or with unsupported parameter or return types

- (BOOL)probablyPrime:(long)n;
// skipped method BigInt.Quo with unsupported parameter or return types

// skipped method BigInt.QuoRem with unsupported parameter or return types

// skipped method BigInt.Rand with unsupported parameter or return types

// skipped method BigInt.Rem with unsupported parameter or return types

// skipped method BigInt.Rsh with unsupported parameter or return types

// skipped method BigInt.Scan with unsupported parameter or return types

// skipped method BigInt.Set with unsupported parameter or return types

// skipped method BigInt.SetBit with unsupported parameter or return types

// skipped method BigInt.SetBits with unsupported parameter or return types

// skipped method BigInt.SetBytes with unsupported parameter or return types

// skipped method BigInt.SetInt64 with unsupported parameter or return types

// skipped method BigInt.SetString with unsupported parameter or return types

// skipped method BigInt.SetUint64 with unsupported parameter or return types

- (long)sign;
// skipped method BigInt.Sqrt with unsupported parameter or return types

- (NSString* _Nonnull)string;
// skipped method BigInt.Sub with unsupported parameter or return types

- (NSString* _Nonnull)text:(long)base;
// skipped method BigInt.TrailingZeroBits with unsupported parameter or return types

// skipped method BigInt.Uint64 with unsupported parameter or return types

// skipped method BigInt.UnmarshalCBOR with unsupported parameter or return types

- (BOOL)unmarshalJSON:(NSData* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshalText:(NSData* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.Xor with unsupported parameter or return types

@end

@interface WlibMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Message.To with unsupported type: github.com/filecoin-project/lotus/chain/address.Address

// skipped field Message.From with unsupported type: github.com/filecoin-project/lotus/chain/address.Address

// skipped field Message.Nonce with unsupported type: uint64

// skipped field Message.Value with unsupported type: gitlab.forceup.in/FilecoinWallet/FilWallet/wlib.BigInt

// skipped field Message.GasPrice with unsupported type: gitlab.forceup.in/FilecoinWallet/FilWallet/wlib.BigInt

// skipped field Message.GasLimit with unsupported type: gitlab.forceup.in/FilecoinWallet/FilWallet/wlib.BigInt

// skipped field Message.Method with unsupported type: uint64

@property (nonatomic) NSData* _Nullable params;
// skipped method Message.Cid with unsupported parameter or return types

// skipped method Message.MarshalCBOR with unsupported parameter or return types

- (NSData* _Nullable)serialize:(NSError* _Nullable* _Nullable)error;
// skipped method Message.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibMsg : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull from;
// skipped field Msg.Nonce with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull value;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull gasLimit;
// skipped field Msg.Method with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull params;
@end

FOUNDATION_EXPORT const int64_t WlibBigIntMaxSerializedLen;

@interface Wlib : NSObject
// skipped variable EmptyInt with unsupported type: gitlab.forceup.in/FilecoinWallet/FilWallet/wlib.BigInt

@end

FOUNDATION_EXPORT NSString* _Nonnull WlibAddressFromString(NSString* _Nullable str);

// skipped function BigFromString with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull WlibGenAddress(NSString* _Nullable pk);

FOUNDATION_EXPORT NSString* _Nonnull WlibMessageCid(NSString* _Nullable jsonstr);

// skipped function NewInt with unsupported parameter or return types


#endif
