
// Objective-C API for talking to the following Go packages
//
//	gitlab.forceup.in/FilecoinWallet/FilWallet/wlib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wlib_FRAMEWORK_H__
#define __Wlib_FRAMEWORK_H__

#include "Wlib.objc.h"
#include "Universe.objc.h"

#endif
