// Objective-C API for talking to gitlab.forceup.in/FilecoinWallet/FilWallet/wlib Go package.
//   gobind -lang=objc gitlab.forceup.in/FilecoinWallet/FilWallet/wlib
//
// File is generated by gobind. Do not edit.

#ifndef __Wlib_H__
#define __Wlib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WlibBigInt;
@class WlibConstructorParams;
@class WlibExecParams;
@class WlibFIL;
@class WlibGenConstructorParamInput;
@class WlibMessage;
@class WlibMsg;
@class WlibOut;
@class WlibProposalHashData;
@class WlibProposeParams;
@class WlibTransaction;
@class WlibTransactionInput;
@class WlibTxnIDParams;
@class WlibWithdrawBalanceParams;

@interface WlibBigInt : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BigInt.Int with unsupported type: *math/big.Int

// skipped method BigInt.Abs with unsupported parameter or return types

// skipped method BigInt.Add with unsupported parameter or return types

// skipped method BigInt.And with unsupported parameter or return types

// skipped method BigInt.AndNot with unsupported parameter or return types

- (NSData* _Nullable)append:(NSData* _Nullable)buf base:(long)base;
// skipped method BigInt.Binomial with unsupported parameter or return types

// skipped method BigInt.Bit with unsupported parameter or return types

- (long)bitLen;
// skipped method BigInt.Bits with unsupported parameter or return types

- (NSData* _Nullable)bytes:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.Cmp with unsupported parameter or return types

// skipped method BigInt.CmpAbs with unsupported parameter or return types

// skipped method BigInt.Copy with unsupported parameter or return types

// skipped method BigInt.Div with unsupported parameter or return types

// skipped method BigInt.DivMod with unsupported parameter or return types

// skipped method BigInt.Equals with unsupported parameter or return types

// skipped method BigInt.Exp with unsupported parameter or return types

- (NSData* _Nullable)fillBytes:(NSData* _Nullable)buf;
// skipped method BigInt.Format with unsupported parameter or return types

// skipped method BigInt.GCD with unsupported parameter or return types

- (BOOL)gobDecode:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)gobEncode:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.GreaterThan with unsupported parameter or return types

// skipped method BigInt.GreaterThanEqual with unsupported parameter or return types

- (int64_t)int64;
- (BOOL)isInt64;
- (BOOL)isUint64;
- (BOOL)isZero;
// skipped method BigInt.LessThan with unsupported parameter or return types

// skipped method BigInt.LessThanEqual with unsupported parameter or return types

// skipped method BigInt.Lsh with unsupported parameter or return types

- (NSData* _Nullable)marshalBinary:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.MarshalCBOR with unsupported parameter or return types

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)marshalText:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.Mod with unsupported parameter or return types

// skipped method BigInt.ModInverse with unsupported parameter or return types

// skipped method BigInt.ModSqrt with unsupported parameter or return types

// skipped method BigInt.Mul with unsupported parameter or return types

// skipped method BigInt.MulRange with unsupported parameter or return types

// skipped method BigInt.Neg with unsupported parameter or return types

- (BOOL)nil_;
- (BOOL)nilOrZero;
// skipped method BigInt.Not with unsupported parameter or return types

// skipped method BigInt.Or with unsupported parameter or return types

- (BOOL)probablyPrime:(long)n;
// skipped method BigInt.Quo with unsupported parameter or return types

// skipped method BigInt.QuoRem with unsupported parameter or return types

// skipped method BigInt.Rand with unsupported parameter or return types

// skipped method BigInt.Rem with unsupported parameter or return types

// skipped method BigInt.Rsh with unsupported parameter or return types

// skipped method BigInt.Scan with unsupported parameter or return types

// skipped method BigInt.Set with unsupported parameter or return types

// skipped method BigInt.SetBit with unsupported parameter or return types

// skipped method BigInt.SetBits with unsupported parameter or return types

// skipped method BigInt.SetBytes with unsupported parameter or return types

// skipped method BigInt.SetInt64 with unsupported parameter or return types

// skipped method BigInt.SetString with unsupported parameter or return types

// skipped method BigInt.SetUint64 with unsupported parameter or return types

- (long)sign;
// skipped method BigInt.Sqrt with unsupported parameter or return types

- (NSString* _Nonnull)string;
// skipped method BigInt.Sub with unsupported parameter or return types

- (NSString* _Nonnull)text:(long)base;
// skipped method BigInt.TrailingZeroBits with unsupported parameter or return types

// skipped method BigInt.Uint64 with unsupported parameter or return types

- (BOOL)unmarshalBinary:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.UnmarshalCBOR with unsupported parameter or return types

- (BOOL)unmarshalJSON:(NSData* _Nullable)b error:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshalText:(NSData* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
// skipped method BigInt.Xor with unsupported parameter or return types

@end

/**
 * type ConstructorParams struct {
	Signers               []addr.Address
	NumApprovalsThreshold uint64
	UnlockDuration        abi.ChainEpoch
	StartEpoch            abi.ChainEpoch
}
 */
@interface WlibConstructorParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ConstructorParams.Signers with unsupported type: []github.com/filecoin-project/go-address.Address

// skipped field ConstructorParams.NumApprovalsThreshold with unsupported type: uint64

// skipped field ConstructorParams.UnlockDuration with unsupported type: github.com/filecoin-project/go-state-types/abi.ChainEpoch

// skipped field ConstructorParams.StartEpoch with unsupported type: github.com/filecoin-project/go-state-types/abi.ChainEpoch

// skipped method ConstructorParams.MarshalCBOR with unsupported parameter or return types

// skipped method ConstructorParams.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibExecParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ExecParams.CodeCID with unsupported type: github.com/ipfs/go-cid.Cid

@property (nonatomic) NSData* _Nullable constructorParams;
// skipped method ExecParams.MarshalCBOR with unsupported parameter or return types

// skipped method ExecParams.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibFIL : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field FIL.Int with unsupported type: *math/big.Int

// skipped method FIL.Abs with unsupported parameter or return types

// skipped method FIL.Add with unsupported parameter or return types

// skipped method FIL.And with unsupported parameter or return types

// skipped method FIL.AndNot with unsupported parameter or return types

- (NSData* _Nullable)append:(NSData* _Nullable)buf base:(long)base;
// skipped method FIL.Binomial with unsupported parameter or return types

// skipped method FIL.Bit with unsupported parameter or return types

- (long)bitLen;
// skipped method FIL.Bits with unsupported parameter or return types

- (NSData* _Nullable)bytes;
// skipped method FIL.Cmp with unsupported parameter or return types

// skipped method FIL.CmpAbs with unsupported parameter or return types

// skipped method FIL.Div with unsupported parameter or return types

// skipped method FIL.DivMod with unsupported parameter or return types

// skipped method FIL.Exp with unsupported parameter or return types

- (NSData* _Nullable)fillBytes:(NSData* _Nullable)buf;
// skipped method FIL.Format with unsupported parameter or return types

// skipped method FIL.GCD with unsupported parameter or return types

- (BOOL)gobDecode:(NSData* _Nullable)buf error:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)gobEncode:(NSError* _Nullable* _Nullable)error;
- (int64_t)int64;
- (BOOL)isInt64;
- (BOOL)isUint64;
// skipped method FIL.Lsh with unsupported parameter or return types

- (NSData* _Nullable)marshalJSON:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)marshalText:(NSError* _Nullable* _Nullable)error;
// skipped method FIL.Mod with unsupported parameter or return types

// skipped method FIL.ModInverse with unsupported parameter or return types

// skipped method FIL.ModSqrt with unsupported parameter or return types

// skipped method FIL.Mul with unsupported parameter or return types

// skipped method FIL.MulRange with unsupported parameter or return types

// skipped method FIL.Neg with unsupported parameter or return types

// skipped method FIL.Not with unsupported parameter or return types

// skipped method FIL.Or with unsupported parameter or return types

- (BOOL)probablyPrime:(long)n;
// skipped method FIL.Quo with unsupported parameter or return types

// skipped method FIL.QuoRem with unsupported parameter or return types

// skipped method FIL.Rand with unsupported parameter or return types

// skipped method FIL.Rem with unsupported parameter or return types

// skipped method FIL.Rsh with unsupported parameter or return types

// skipped method FIL.Scan with unsupported parameter or return types

// skipped method FIL.Set with unsupported parameter or return types

// skipped method FIL.SetBit with unsupported parameter or return types

// skipped method FIL.SetBits with unsupported parameter or return types

// skipped method FIL.SetBytes with unsupported parameter or return types

// skipped method FIL.SetInt64 with unsupported parameter or return types

// skipped method FIL.SetString with unsupported parameter or return types

// skipped method FIL.SetUint64 with unsupported parameter or return types

- (NSString* _Nonnull)short_;
- (long)sign;
// skipped method FIL.Sqrt with unsupported parameter or return types

- (NSString* _Nonnull)string;
// skipped method FIL.Sub with unsupported parameter or return types

- (NSString* _Nonnull)text:(long)base;
// skipped method FIL.TrailingZeroBits with unsupported parameter or return types

// skipped method FIL.Uint64 with unsupported parameter or return types

- (NSString* _Nonnull)unitless;
- (BOOL)unmarshalJSON:(NSData* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
- (BOOL)unmarshalText:(NSData* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
// skipped method FIL.Xor with unsupported parameter or return types

@end

@interface WlibGenConstructorParamInput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field GenConstructorParamInput.Signers with unsupported type: []string

// skipped field GenConstructorParamInput.Threshold with unsupported type: uint64

@property (nonatomic) int64_t unlockDuration;
@property (nonatomic) int64_t startEpoch;
- (NSString* _Nonnull)transferToSpec;
@end

@interface WlibMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Message.Version with unsupported type: uint64

// skipped field Message.To with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field Message.From with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field Message.Nonce with unsupported type: uint64

// skipped field Message.Value with unsupported type: github.com/filecoin-project/go-state-types/big.Int

@property (nonatomic) int64_t gasLimit;
// skipped field Message.GasFeeCap with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped field Message.GasPremium with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped field Message.Method with unsupported type: github.com/filecoin-project/go-state-types/abi.MethodNum

@property (nonatomic) NSData* _Nullable params;
// skipped method Message.Cid with unsupported parameter or return types

// skipped method Message.MarshalCBOR with unsupported parameter or return types

- (NSData* _Nullable)serialize:(NSError* _Nullable* _Nullable)error;
// skipped method Message.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibMsg : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Msg.Version with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull from;
// skipped field Msg.Nonce with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull value;
@property (nonatomic) int64_t gasLimit;
@property (nonatomic) NSString* _Nonnull gasFeeCap;
@property (nonatomic) NSString* _Nonnull gasPremium;
// skipped field Msg.Method with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull params;
@end

@interface WlibOut : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull err;
@property (nonatomic) NSData* _Nullable param;
@end

@interface WlibProposalHashData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ProposalHashData.Requester with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field ProposalHashData.To with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field ProposalHashData.Value with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped field ProposalHashData.Method with unsupported type: github.com/filecoin-project/go-state-types/abi.MethodNum

@property (nonatomic) NSData* _Nullable params;
// skipped method ProposalHashData.MarshalCBOR with unsupported parameter or return types

- (NSData* _Nullable)serialize:(NSError* _Nullable* _Nullable)error;
// skipped method ProposalHashData.UnmarshalCBOR with unsupported parameter or return types

@end

/**
 * type ProposeParams struct {
	To     addr.Address
	Value  abi.TokenAmount
	Method abi.MethodNum
	Params []byte
}
 */
@interface WlibProposeParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ProposeParams.To with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field ProposeParams.Value with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped field ProposeParams.Method with unsupported type: github.com/filecoin-project/go-state-types/abi.MethodNum

@property (nonatomic) NSData* _Nullable params;
// skipped method ProposeParams.MarshalCBOR with unsupported parameter or return types

// skipped method ProposeParams.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Transaction.To with unsupported type: github.com/filecoin-project/go-address.Address

// skipped field Transaction.Value with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped field Transaction.Method with unsupported type: github.com/filecoin-project/go-state-types/abi.MethodNum

@property (nonatomic) NSData* _Nullable params;
// skipped field Transaction.Approved with unsupported type: []github.com/filecoin-project/go-address.Address

// skipped method Transaction.MarshalCBOR with unsupported parameter or return types

// skipped method Transaction.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibTransactionInput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t txID;
@property (nonatomic) NSString* _Nonnull requester;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull value;
// skipped field TransactionInput.Method with unsupported type: uint64

@property (nonatomic) NSString* _Nonnull params;
- (NSData* _Nullable)transfer:(NSError* _Nullable* _Nullable)error;
@end

@interface WlibTxnIDParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TxnIDParams.ID with unsupported type: github.com/filecoin-project/specs-actors/actors/builtin/multisig.TxnID

@property (nonatomic) NSData* _Nullable proposalHash;
// skipped method TxnIDParams.MarshalCBOR with unsupported parameter or return types

// skipped method TxnIDParams.UnmarshalCBOR with unsupported parameter or return types

@end

@interface WlibWithdrawBalanceParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field WithdrawBalanceParams.AmountRequested with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped method WithdrawBalanceParams.MarshalCBOR with unsupported parameter or return types

// skipped method WithdrawBalanceParams.UnmarshalCBOR with unsupported parameter or return types

@end

FOUNDATION_EXPORT const int64_t WlibBigIntMaxSerializedLen;
// skipped const FilBase with unsupported type: uint64

// skipped const FilecoinPrecision with unsupported type: uint64


@interface Wlib : NSObject
// skipped variable EmptyInt with unsupported type: github.com/filecoin-project/go-state-types/big.Int

// skipped variable TotalFilecoinInt with unsupported type: github.com/filecoin-project/go-state-types/big.Int

@end

FOUNDATION_EXPORT NSString* _Nonnull WlibAddressFromString(NSString* _Nullable str);

// skipped function BigAdd with unsupported parameter or return types


// skipped function BigCmp with unsupported parameter or return types


// skipped function BigDiv with unsupported parameter or return types


// skipped function BigFromBytes with unsupported parameter or return types


// skipped function BigFromString with unsupported parameter or return types


// skipped function BigMod with unsupported parameter or return types


// skipped function BigMul with unsupported parameter or return types


// skipped function BigSub with unsupported parameter or return types


// skipped function DeciStr with unsupported parameter or return types


// skipped function FromFil with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull WlibGenAddress(NSString* _Nullable pk, NSString* _Nullable t);

FOUNDATION_EXPORT NSString* _Nonnull WlibGenApprovalV3(NSString* _Nullable tx);


FOUNDATION_EXPORT NSString* _Nonnull WlibGenConstructorParamV3(NSString* _Nullable input);

FOUNDATION_EXPORT NSString* _Nonnull WlibGenProposalForChangeOwnerV3(NSString* _Nullable self_, NSString* _Nullable miner, NSString* _Nullable value);

FOUNDATION_EXPORT NSString* _Nonnull WlibGenProposalForWithdrawBalanceV3(NSString* _Nullable miner, NSString* _Nullable value);

FOUNDATION_EXPORT NSString* _Nonnull WlibGenProposeForSendParamV3(NSString* _Nullable to, NSString* _Nullable value);

FOUNDATION_EXPORT NSString* _Nonnull WlibMessageCid(NSString* _Nullable jsonstr);

// skipped function MustParseFIL with unsupported parameter or return types


// skipped function NewInt with unsupported parameter or return types


// skipped function ParseFIL with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull WlibSecpPrivateToPublic(NSString* _Nullable ck);

FOUNDATION_EXPORT NSString* _Nonnull WlibSecpSign(NSString* _Nullable ck, NSString* _Nullable msg);

// skipped function SerializeParams with unsupported parameter or return types


// skipped function SizeStr with unsupported parameter or return types


#endif
